  pipeline {
    agent {
      node {
        label "master"
      } 
    }

    stages {
      stage('fetch') {
        steps {
          git url: 'https://github.com/PrashantBhatasana/terraform-jenkins-ec2' 
        }
      }

      stage('Terraform init') {
        steps {
          sh 'terraform init'
          sh 'terraform plan'
        }
      }

      stage('Approval') {
        steps {
          script {
            def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
          }
        }
      }

      stage('Terraform Apply') {
        steps {
          sh 'terraform apply -input=false'
        }
      }
    } 
  }